apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-gateway
  namespace: prod-app
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: 34.13.117.234.nip.io
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: prod-gateway-cert-new
