apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-gateway
  namespace: prod-app
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "136.110.180.171.nip.io"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Certificate
        group: networking.gke.io
        name: prod-gateway-cert
