apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: demo-cdn-policy
  namespace: prod-app
spec:
  targetRef:
    group: ""
    kind: Service
    name: demo-svc
  default:
    cdn:
      enabled: true
