apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prod-route
  namespace: prod-app
spec:
  parentRefs:
  - name: prod-gateway
  hostnames:
  - "136.110.129.148.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: demo-svc
      port: 80
