apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: microservices-route
  namespace: prod-app
spec:
  parentRefs:
  - name: prod-gateway
  hostnames:
  - "34.13.117.234.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /users
    backendRefs:
    - name: user-svc
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /

  - matches:
    - path:
        type: PathPrefix
        value: /orders
    backendRefs:
    - name: order-svc
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /

  - matches:
    - path:
        type: PathPrefix
        value: /payments
    backendRefs:
    - name: payment-svc
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /

  # Default route
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: demo-svc
      port: 80
