apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-route
  namespace: prod-app
spec:
  parentRefs:
  - name: prod-gateway
  hostnames:
  - "gw.136.110.180.171.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /hello
    backendRefs:
    - name: demo-svc
      port: 80
