apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: prod-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      # --- ADD THE IMAGE PULL SECRET HERE ---
      imagePullSecrets:
      - name: gar-key
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/rakesh-project-480508/my-repo/microservice-base:1.1
        env:
        - name: SERVICE_NAME
          value: "USER"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: prod-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  selector:
    app: user-app
  ports:
  - port: 80
    targetPort: 8080
