apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: prod-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  selector:
    app: user-app
  ports:
  - port: 80
    targetPort: 8080
